< [GMIT Data Analytics](https://web.archive.org/web/20201029063153/https://www.gmit.ie/computer-science-and-applied-physics/higher-diploma-science-computing-data-analytics-ict) | [Table of Contents](https://github.com/E6985) | [README](https://github.com/E6985/pda-numpy-random/blob/master/README.md) >

<img src="img/gmit.png" />

## Programming for Data Analysis - Assignment 2020
## Due: last commit on or before November 22nd, 2020
***

#### Assignment
Assignment concerns the numpy.random package in Python. Required to create a Jupyter Notebook explaining the use of the package, including detailed explanations of at least five of the distributions provided for in the package. There are four distinct tasks to be carried out in the Jupyter notebook.

1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.
***

#### Task 1
Explain the overall purpose of the package.
***

- almost anything interesting that is done on a computer such as resizing photographs taken on a phone - converting songs on a cd to mp3 - anything that is happening on a computer monitor - anything scientific that is done on a computer turns out all these ideas are based on matrix operations given its the quickest way - another example is compressing an images/song to a smaller size or analysing a dataset - it turns out that matrix operations are typically involved therefore the package - numpy - is essential because it knows how to perform these operations very quickly [1.1]

- the package - numpy - is such an important package given that a number of other packages in python depend on it such as - pandas - scipy - matplotlib [1.2] - this specialised package that is very efficient with dealing with numbers in long lists in python even lists contained within lists - multi-dimensional arrays - the structure of a numpy multi-dimensional array is rectanglar in shape [1.1]

- common practice to start with a csv file which is imported into numpy or imported into pandas which uses the numpy package in the background however its may not always be possible to collect data so the use of the numpy subpackage - random - can be used for generating simulated data - pretending to collect data by generating random numbers that follow a certain pattern and analysing these number for whatever reason [1.1]

***
#### References
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1.1] I. McLoughlin, "Introduction to numpy," GMIT, October 2018.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1.2] I. McLoughlin, "Introduction to numpy.random," GMIT, October 2018.
***
#### END

#### Task 2
Explain the use of the “Simple random data” and “Permutations” functions.
***

In [1]:
# b_T_hird_P_arty-imports
from numpy.random import default_rng as newGenBitGenPCG64

In [2]:
from numpy.core import arange as arrayEvenlySpaced
from numpy.core import reshape as arrayNewShape

###### Permutations - numpy.random.Generator.shuffle

In [3]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print(newGenBitGenPCG64().shuffle.__doc__) # method shuffle - attr __doc__ - access


        shuffle(x, axis=0)

        Modify a sequence in-place by shuffling its contents.

        The order of sub-arrays is changed but their contents remains the same.

        Parameters
        ----------
        x : array_like
            The array or list to be shuffled.
        axis : int, optional
            The axis which `x` is shuffled along. Default is 0.
            It is only supported on `ndarray` objects.

        Returns
        -------
        None

        Examples
        --------
        >>> rng = np.random.default_rng()
        >>> arr = np.arange(10)
        >>> rng.shuffle(arr)
        >>> arr
        [1 7 5 2 9 4 3 6 0 8] # random

        >>> arr = np.arange(9).reshape((3, 3))
        >>> rng.shuffle(arr)
        >>> arr
        array([[3, 4, 5], # random
               [6, 7, 8],
               [0, 1, 2]])

        >>> arr = np.arange(9).reshape((3, 3))
        >>> rng.shuffle(arr, axis=1)
        >>> arr
        array([[2, 0, 1], # random
               [

- examples - numpy - documentation [2.1]

In [4]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
nInsObjGBT=newGenBitGenPCG64()

In [5]:
# package numpy - subpackage core - C function arange alias arrayEvenlySpaced - call
nArray=arrayEvenlySpaced(10)

In [6]:
# package numpy - subpackage random - object Generator - method shuffle - call
nInsObjGBT.shuffle(nArray)

In [7]:
nArray

array([1, 2, 8, 9, 4, 3, 7, 6, 5, 0])

In [8]:
# package numpy - subpackage core - C function arange alias arrayEvenlySpaced - call
nArray=arrayEvenlySpaced(9)

In [9]:
# package numpy - subpackage core - C function reshape alias arrayNewShape - call
nArray=arrayNewShape(nArray,(3,3))

In [10]:
# package numpy - subpackage random - object Generator - method shuffle - call
nInsObjGBT.shuffle(nArray)

In [11]:
nArray

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [12]:
# package numpy - subpackage random - object Generator - method shuffle - call
nInsObjGBT.shuffle(nArray,axis=1)

In [13]:
nArray

array([[8, 6, 7],
       [2, 0, 1],
       [5, 3, 4]])

###### Permutations - numpy.random.Generator.permutation

- examples - numpy - documentation [2.2]

In [14]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation(10)

array([5, 8, 3, 9, 1, 7, 0, 2, 6, 4])

In [15]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation([1,4,9,12,15])

array([ 9,  4,  1, 15, 12])

In [16]:
# package numpy - subpackage core - C function arange alias arrayEvenlySpaced - call
nArray=arrayEvenlySpaced(9)

In [17]:
# package numpy - subpackage core - C function reshape alias arrayNewShape - call
nArray=arrayNewShape(nArray,(3,3))

In [18]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation(nArray)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation(nArray,axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [20]:
# Kernel - Restart
exit()

***
#### References
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2.1] Documentation, "numpy.random.Generator.shuffle," [NumPy](https://web.archive.org/web/20201103103712/https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy-random-generator-shuffle), June 2020.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2.2] Documentation, "numpy.random.Generator.permutation," [NumPy](https://web.archive.org/web/20201103112923/https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy-random-generator-permutation), June 2020.
***
#### END

#### Task 3
Explain the use and purpose of at least five “Distributions” functions.
***

###### Probability Distributions
***

- classified - discrete probability distributions - continuous probability distributions - depend on whether the array/distribution define probabilities associated with variables that are either - discrete - continuous [[...] StarTrek, "Probability Distributions: Discrete vs. Continuous," [startrek](https://web.archive.org/web/20201106155243/https://stattrek.com/probability-distributions/discrete-continuous.aspx), November 2015.]

- discrete variables - countable in a finite amount of time - count the change in a wallet - count the money in a bank account [[...] Statistics How To, "Discrete vs Continuous variables: How to Tell the Difference," [statisticshowto](xxx), November 2013.] - real-world - flip a coin - count number of heads - the count could be any integer value between ``0`` and plus ``infinity`` - not possible to get 2.5 heads [[...] Statistics How To, "Discrete vs Continuous variables: How to Tell the Difference," [statisticshowto](xxx), November 2013.]

- continuous variables - literally take forever to count - cannot count age - time is a continuous variable [[...] Statistics How To, "Discrete vs Continuous variables: How to Tell the Difference," [statisticshowto](xxx), November 2013.] - real-world - fire department recruitment requirement - fire fighters must weigh between ``70kgs`` and ``110kgs`` - weight of the fire fighter is a continuous variable since weight could take on any value between ``70kgs`` and ``110kgs`` [[...] Statistics How To, "Discrete vs Continuous variables: How to Tell the Difference," [statisticshowto](xxx), November 2013.]

- task requirement is to explain the use and purpose of at least five "Distributions" functions - endeavour to split the task between - continuous probability distributions - discrete probability distributions [[...] No Reference.]

###### Continuous Probability Distributions
***

In [1]:
# b_T_hird_P_arty-imports
from numpy.random import default_rng as newGenBitGenPCG64

- taking random sample - data could be arranged such that its spread out in many different ways - more on the left - more on the right - all jumbled up [[...] Math Is Fun, "Normal Distribution," [mathisfun](https://web.archive.org/web/20201106104058/https://www.mathsisfun.com/data/standard-normal-distribution.html), November 2014.]

<img src="img/distribution-normal-spread-left-right-jumbled.png" />

> Math Is Fun, "Normal Distribution," [mathisfun](https://web.archive.org/web/20201106104058/https://www.mathsisfun.com/data/standard-normal-distribution.html), November 2014.

###### Continuous - Normal Distribution - numpy.random.Generator.normal

- many cases - data tends to be around a central value with no bias - left or right - gets close to a normal distribtion - often called bell curve because of its shape [[...] Math Is Fun, "Normal Distribution," [mathisfun](https://web.archive.org/web/20201106104058/https://www.mathsisfun.com/data/standard-normal-distribution.html), November 2014.][[...] Anaconda - "numpy/random," Docstring, June 2020.]

<img src="img/distribution-normal-spread-bell-curve.png" />

> Math Is Fun, "Normal Distribution," [mathisfun](https://web.archive.org/web/20201106104058/https://www.mathsisfun.com/data/standard-normal-distribution.html), November 2014.

In [2]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print("\n".join(newGenBitGenPCG64().normal.__doc__.split("\n")[3:10])) # method normal - attr __doc__ - access

        Draw random samples from a normal (Gaussian) distribution.

        The probability density function of the normal distribution, first
        derived by De Moivre and 200 years later by both Gauss and Laplace
        independently [2]_, is often called the bell curve because of
        its characteristic shape (see the example below).



- nature - things such as - heights of people - size of things produced by machines - errors in measurements - blood pressure - marks on a test - follow a normal distribution - describes samples influenced by unplanned interferences - each having its own distinctive arrangement [[...] Math Is Fun, "Normal Distribution," [mathisfun](https://web.archive.org/web/20201106104058/https://www.mathsisfun.com/data/standard-normal-distribution.html), November 2014.][[...] Anaconda - "numpy/random," Docstring, June 2020.]

In [3]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print("\n".join(newGenBitGenPCG64().normal.__doc__.split("\n")[10:15])) # method normal - attr __doc__ - access

        The normal distributions occurs often in nature.  For example, it
        describes the commonly occurring distribution of samples influenced
        by a large number of tiny, random disturbances, each with its own
        unique distribution [2]_.



###### Continuous - Uniform Distribution - numpy.random.Generator.uniform

- taking random sample - data arranged such that its completely arbitrary except that it is known to lie between certain bounds - each value is equally likely to be drawn at random [[...] F.M. Dekking, C. Kraaikamp, H.P. Lopuhaä, L.E. Meester, "A Modern Introduction to Probability and Statistics Understanding Why and How," Springer, 2005.] 

- half-open interval - one endpoint is included but not the other [[...] Wolfram, "Half-Closed Interval," [mathworld.wolfram](https://web.archive.org/web/20201106190646/https://mathworld.wolfram.com/Half-ClosedInterval.html), Ootober 2020.] - includes - low - excludes - high [[...] Anaconda - "numpy/random," Docstring, June 2020.]

$$[low, high)$$

<img src="img/distribution-uniform-half-open-interval.png" />

> Wolfram, "Half-Closed Interval," [mathworld.wolfram](https://web.archive.org/web/20201106190646/https://mathworld.wolfram.com/Half-ClosedInterval.html), Ootober 2020.

- same principle as the most commonly used iterator in python - range - which generates a sequence of numbers - by convention the top of the object range is not included in the output [[...] J. VanderPlas, "Built-In Data Structures," A Whirlwind Tour of Python, p. 39, August 2016.]

In [4]:
print(*range(0,2))

0 1


In [5]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print("\n".join(newGenBitGenPCG64().uniform.__doc__.split("\n")[3:10])) # method uniform - attr __doc__ - access

        Draw samples from a uniform distribution.

        Samples are uniformly distributed over the half-open interval
        ``[low, high)`` (includes low, but excludes high).  In other words,
        any value within the given interval is equally likely to be drawn
        by `uniform`.



###### Continuous - Chi-square Distribution - numpy.random.Generator.chisquare

In [6]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print(newGenBitGenPCG64().chisquare.__doc__) # method chisquare - attr __doc__ - access


        chisquare(df, size=None)

        Draw samples from a chi-square distribution.

        When `df` independent random variables, each with standard normal
        distributions (mean 0, variance 1), are squared and summed, the
        resulting distribution is chi-square (see Notes).  This distribution
        is often used in hypothesis testing.

        Parameters
        ----------
        df : float or array_like of floats
             Number of degrees of freedom, must be > 0.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None`` (default),
            a single value is returned if ``df`` is a scalar.  Otherwise,
            ``np.array(df).size`` samples are drawn.

        Returns
        -------
        out : ndarray or scalar
            Drawn samples from the parameterized chi-square distribution.

        Raises
        ------
        V

In [7]:
# Kernel Restart
exit()

###### Discrete Probability Distributions
***

In [1]:
# b_T_hird_P_arty-imports
from numpy.random import Generator as CContainerBitGenerator
from numpy.random import PCG64 as CPermutedCongruentialGenerator

- PCG64 - default pseudo-random number generator - class - BitGenerator - algorithm is an implementation of O'Neill's permutation congruential generator [[...] Documentation, "Permuted Congruential Generator (64-bit, PCG64)," [NumPy](https://web.archive.org/web/20201102192029/https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html#permuted-congruential-generator-64-bit-pcg64), June 2020.]

In [2]:
# package numpy - subpackage random - object PCG64 alias CPermutedCongruentialGenerator - instantiate
nPCG64=CPermutedCongruentialGenerator()

- base - parent - class - BitGenerator [[...] Documentation, "numpy.random.BitGenerator," [NumPy](https://web.archive.org/web/20201102114147/https://numpy.org/doc/stable/reference/random/bit_generators/generated/numpy.random.BitGenerator.html#numpy.random.BitGenerator), June 2020.] - of the - child - class - Generator [[...] Documentation, "numpy.random.Generator," [NumPy](https://web.archive.org/web/20201102191659/https://numpy.org/doc/stable/reference/random/generator.html#random-generator), June 2020.]

In [3]:
# package numpy - subpackage random - object Generator alias CContainerBitGenerator - instantiate
nContainerBitGen=CContainerBitGenerator(nPCG64)

- recommended constructor - Generator - function - default_rng - which will instantiate a - Generator - with numpys default - BitGenerator - same outcome as above - will be implemented going forward given numpys recommendation [[...] Documentation, "numpy.random.Generator," [NumPy](https://web.archive.org/web/20201102191659/https://numpy.org/doc/stable/reference/random/generator.html#random-generator), June 2020.] 

###### Discrete - Binomial Distribution - numpy.random.Generator.binomial

In [4]:
# pkg numpy - subpkg random - obj Generator alias CContainerBitGenerator - method binomial - attri __doc__ - access
print(nContainerBitGen.binomial.__doc__)


        binomial(n, p, size=None)

        Draw samples from a binomial distribution.

        Samples are drawn from a binomial distribution with specified
        parameters, n trials and p probability of success where
        n an integer >= 0 and p is in the interval [0,1]. (n may be
        input as a float, but it is truncated to an integer in use)

        Parameters
        ----------
        n : int or array_like of ints
            Parameter of the distribution, >= 0. Floats are also accepted,
            but they will be truncated to integers.
        p : float or array_like of floats
            Parameter of the distribution, >= 0 and <=1.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None`` (default),
            a single value is returned if ``n`` and ``p`` are both scalars.
            Otherwise, ``np.broadcast(n, p).size`` samples are d

###### Discrete - Poisson Distribution - numpy.random.Generator.poisson

In [5]:
# pkg numpy - subpkg random - obj Generator alias CContainerBitGenerator - method poisson - attri __doc__ - access
print(nContainerBitGen.poisson.__doc__)


        poisson(lam=1.0, size=None)

        Draw samples from a Poisson distribution.

        The Poisson distribution is the limit of the binomial distribution
        for large N.

        Parameters
        ----------
        lam : float or array_like of floats
            Expectation of interval, must be >= 0. A sequence of expectation
            intervals must be broadcastable over the requested size.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None`` (default),
            a single value is returned if ``lam`` is a scalar. Otherwise,
            ``np.array(lam).size`` samples are drawn.

        Returns
        -------
        out : ndarray or scalar
            Drawn samples from the parameterized Poisson distribution.

        Notes
        -----
        The Poisson distribution

        .. math:: f(k; \lambda)=\frac{\lambda^k e^{-\lambda}

###### Discrete - Geometric Distribution - numpy.random.Generator.geometric

In [6]:
# pkg numpy - subpkg random - obj Generator alias CContainerBitGenerator - method geometric - attri __doc__ - access
print(nContainerBitGen.geometric.__doc__)


        geometric(p, size=None)

        Draw samples from the geometric distribution.

        Bernoulli trials are experiments with one of two outcomes:
        success or failure (an example of such an experiment is flipping
        a coin).  The geometric distribution models the number of trials
        that must be run in order to achieve success.  It is therefore
        supported on the positive integers, ``k = 1, 2, ...``.

        The probability mass function of the geometric distribution is

        .. math:: f(k) = (1 - p)^{k - 1} p

        where `p` is the probability of success of an individual trial.

        Parameters
        ----------
        p : float or array_like of floats
            The probability of success of an individual trial.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None`` (default),
            a single value is re

***
#### References
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1] authorNames, referenceTitle, locationWebsiteBookVideo, dateMonthYear.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[10]

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[100]

&nbsp;&nbsp;&nbsp;[1000]
***
#### END

#### Task 4
Explain the use of seeds in generating pseudorandom numbers.
***

***
#### References
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1] authorNames, referenceTitle, locationWebsiteBookVideo, dateMonthYear.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[10]

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[100]

&nbsp;&nbsp;&nbsp;[1000]
***
#### END

***
# END